// angelyn
// weekly summary feature - rewritten to use Sequelize instead of raw pg queries
// gathers the week's data, asks claude to write the briefing, emails it, logs it

const { AlertRule, NotificationLog } = require('../models');
const mock = require('./mockDataService');
const claude = require('./claudeService');
const email = require('./emailService');

async function sendWeeklySummary(triggeredByUserId) {
  // 1. gather this week's stats
  const stats = gatherStats();

  // 2. generate the summary - try claude first, fall back to stub
  let summary;
  let generatedBy;
  try {
    if (claude.hasApiKey()) {
      summary = await claude.generateSummary(stats);
      generatedBy = 'claude';
    } else {
      summary = generateStubSummary(stats);
      generatedBy = 'stub (no api key)';
    }
  } catch (err) {
    console.error('claude generation failed, using stub instead:', err.message);
    summary = generateStubSummary(stats);
    generatedBy = 'stub (claude error)';
  }

  // 3. find the active weekly_summary rule
  const rule = await AlertRule.findOne({
    where: { trigger_type: 'weekly_summary', is_active: true, is_deleted: false },
  });

  if (!rule) {
    throw new Error('No active weekly_summary rule found. Create one in Alert Rules first.');
  }

  const recipients = rule.recipients.split(',').map(r => r.trim()).filter(Boolean);
  const subject = `Weekly Estate Health Summary - ${new Date().toLocaleDateString('en-SG')}`;

  // 4. send + log each recipient
  let sentCount = 0;
  let failedCount = 0;

  for (const recipient of recipients) {
    try {
      await email.sendEmail({ to: recipient, subject, body: summary });
      await NotificationLog.create({
        rule_id: rule.id,
        channel: 'email',
        recipient,
        status: 'sent',
        message_preview: summary.slice(0, 200),
      });
      sentCount++;
    } catch (e) {
      console.error(`email to ${recipient} failed:`, e.message);
      await NotificationLog.create({
        rule_id: rule.id,
        channel: 'email',
        recipient,
        status: 'failed',
        message_preview: e.message.slice(0, 200),
      });
      failedCount++;
    }
  }

  return {
    ok: true,
    recipientCount: recipients.length,
    sentCount,
    failedCount,
    preview: summary,
    generatedBy,
    emailMode: email.hasResend() ? 'resend' : 'stub',
  };
}

function gatherStats() {
  const flora = mock.getFloraRecords();
  const sightings = mock.getFaunaSightings();
  const cases = mock.getCases();

  const criticalPlants = flora
    .filter(f => f.health_status === 'critical')
    .map(f => `${f.species} at ${f.block}`);

  const atRiskPlants = flora
    .filter(f => f.health_status === 'at-risk')
    .map(f => `${f.species} at ${f.block}`);

  const blockCounts = {};
  sightings.forEach(s => {
    blockCounts[s.block] = (blockCounts[s.block] || 0) + 1;
  });
  const hotspots = Object.entries(blockCounts)
    .filter(([_, n]) => n >= 3)
    .map(([block, count]) => ({ block, count }));

  const openCases = cases.filter(c => c.status === 'open');
  const resolvedCases = cases.filter(c => c.status === 'resolved');

  return {
    criticalPlants,
    atRiskPlants,
    totalSightings: sightings.length,
    hotspots,
    openCaseCount: openCases.length,
    openCaseTitles: openCases.map(c => c.title),
    resolvedCount: resolvedCases.length,
  };
}

function generateStubSummary(stats) {
  const critical = stats.criticalPlants.length;
  const atRisk = stats.atRiskPlants.length;
  return `Estate health update for the week ending ${new Date().toLocaleDateString('en-SG')}.

Plant health requires attention: ${critical} plant${critical === 1 ? ' is' : 's are'} in critical condition and ${atRisk} ${atRisk === 1 ? 'is' : 'are'} at risk. ${stats.criticalPlants.length ? `Prioritise ${stats.criticalPlants[0]} this week before it reaches a point of no return.` : ''}

Animal activity: ${stats.totalSightings} sightings logged across the estate. ${stats.hotspots.length} active hotspot${stats.hotspots.length === 1 ? '' : 's'} detected${stats.hotspots.length ? ` at ${stats.hotspots.map(h => h.block).join(', ')}` : ''}.

Case load: ${stats.openCaseCount} case${stats.openCaseCount === 1 ? '' : 's'} remain open and ${stats.resolvedCount} ${stats.resolvedCount === 1 ? 'was' : 'were'} resolved this week.

[Generated by fallback stub - set ANTHROPIC_API_KEY to enable the real AI summary.]`;
}

module.exports = { sendWeeklySummary, gatherStats, generateStubSummary };
