import { useEffect, useState } from 'react';
import {
  Box, Typography, Grid, Card, CardContent, Button,
  Table, TableHead, TableRow, TableCell, TableBody,
  Chip, Alert, CircularProgress, Collapse
} from '@mui/material';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';
import { useUser } from '../contexts/UserContext';
import http from '../http';

// EM Services brand palette
const BRAND = {
  primary: '#C1272D',
  primaryHover: '#A61D22',
  heading: '#222222',
  text: '#444444',
  textLight: '#777777',
  border: '#E5E5E5',
  section: '#F7F7F7',
  success: '#2E7D32',
  warning: '#F4B400',
};

export default function Dashboard() {
  const { user } = useUser();
  const [metrics, setMetrics] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [summaryResult, setSummaryResult] = useState(null);
  const [sending, setSending] = useState(false);
  const [showPreview, setShowPreview] = useState(false);

  useEffect(() => {
    loadMetrics();
    const interval = setInterval(loadMetrics, 60000);
    return () => clearInterval(interval);
  }, []);

  async function loadMetrics() {
    try {
      const { data } = await http.get('/dashboard/metrics');
      setMetrics(data);
      setError(null);
    } catch (e) {
      setError(e.response?.data?.error || 'failed to load metrics');
    } finally {
      setLoading(false);
    }
  }

  async function triggerSummary() {
    setSending(true);
    setSummaryResult(null);
    try {
      const { data } = await http.post('/dashboard/trigger-summary');
      setSummaryResult({ ok: true, ...data });
      loadMetrics();
    } catch (e) {
      setSummaryResult({ ok: false, error: e.response?.data?.error || e.message });
    } finally {
      setSending(false);
    }
  }

  if (loading) return <Box sx={{ display: 'flex', justifyContent: 'center', mt: 6 }}><CircularProgress sx={{ color: BRAND.primary }} /></Box>;
  if (error) return <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>;

  const statusColor = { open: 'warning', in_progress: 'info', resolved: 'success' };

  return (
    <Box sx={{ p: 3 }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <div>
          <Typography variant="h5" fontWeight={700} sx={{ color: BRAND.heading }}>Command Centre</Typography>
          <Typography variant="body2" sx={{ color: BRAND.textLight }}>Real-time estate biodiversity overview</Typography>
        </div>
        {user?.role === 'admin' && (
          <Button
            variant="contained"
            onClick={triggerSummary}
            disabled={sending}
            sx={{ bgcolor: BRAND.primary, '&:hover': { bgcolor: BRAND.primaryHover }, borderRadius: '4px', px: 3, py: 1.5 }}
          >
            {sending ? 'Sending...' : '📧 Send Weekly Summary Now'}
          </Button>
        )}
      </Box>

      {summaryResult && (
        <Alert severity={summaryResult.ok ? 'success' : 'error'} sx={{ mb: 2 }}>
          {summaryResult.ok ? (
            <Box>
              <Typography variant="body2" fontWeight={500}>
                Summary sent to {summaryResult.recipientCount} recipient(s). Generated by: {summaryResult.generatedBy}
              </Typography>
              <Button size="small" onClick={() => setShowPreview(p => !p)} sx={{ mt: 0.5, p: 0, color: BRAND.primary }}>
                {showPreview ? 'Hide preview' : 'Show preview'}
              </Button>
              <Collapse in={showPreview}>
                <Box component="pre" sx={{ mt: 1, fontSize: 12, whiteSpace: 'pre-wrap', bgcolor: 'rgba(255,255,255,0.5)', p: 1.5, borderRadius: 1 }}>
                  {summaryResult.preview}
                </Box>
              </Collapse>
            </Box>
          ) : summaryResult.error}
        </Alert>
      )}

      <Grid container spacing={2} sx={{ mb: 3 }}>
        {[
          { label: 'Open Cases', value: metrics.openCases, color: BRAND.warning },
          { label: 'Critical Flora', value: metrics.criticalFlora, sub: `${metrics.atRiskFlora} at risk`, color: BRAND.primary },
          { label: 'Active Hotspots', value: metrics.activeHotspots, color: BRAND.heading },
          { label: 'Alerts Sent (7d)', value: metrics.notificationsLast7Days, color: BRAND.success },
        ].map(kpi => (
          <Grid item xs={12} sm={6} md={3} key={kpi.label}>
            <Card sx={{ borderLeft: `4px solid ${kpi.color}`, border: `1px solid ${BRAND.border}`, boxShadow: '0 6px 20px rgba(0,0,0,.06)', borderRadius: '10px' }}>
              <CardContent>
                <Typography variant="caption" sx={{ color: BRAND.textLight, textTransform: 'uppercase', letterSpacing: 0.5 }}>
                  {kpi.label}
                </Typography>
                <Typography variant="h4" fontWeight={700} sx={{ color: BRAND.heading }}>{kpi.value}</Typography>
                {kpi.sub && <Typography variant="caption" sx={{ color: BRAND.textLight }}>{kpi.sub}</Typography>}
              </CardContent>
            </Card>
          </Grid>
        ))}
      </Grid>

      <Grid container spacing={2}>
        <Grid item xs={12} md={7}>
          <Card sx={{ border: `1px solid ${BRAND.border}`, boxShadow: '0 6px 20px rgba(0,0,0,.06)', borderRadius: '10px' }}>
            <CardContent>
              <Typography variant="subtitle1" fontWeight={600} mb={2} sx={{ color: BRAND.heading }}>Cases by Category</Typography>
              {metrics.casesByCategory.length === 0 ? (
                <Typography variant="body2" sx={{ color: BRAND.textLight }}>No cases yet.</Typography>
              ) : (
                <ResponsiveContainer width="100%" height={240}>
                  <BarChart data={metrics.casesByCategory}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#eee" />
                    <XAxis dataKey="category" tick={{ fontSize: 12 }} />
                    <YAxis allowDecimals={false} />
                    <Tooltip />
                    <Bar dataKey="count" fill={BRAND.primary} radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              )}
            </CardContent>
          </Card>
        </Grid>

        <Grid item xs={12} md={5}>
          <Card sx={{ border: `1px solid ${BRAND.border}`, boxShadow: '0 6px 20px rgba(0,0,0,.06)', borderRadius: '10px' }}>
            <CardContent>
              <Typography variant="subtitle1" fontWeight={600} mb={2} sx={{ color: BRAND.heading }}>Recent Cases</Typography>
              <Table size="small">
                <TableHead>
                  <TableRow>
                    <TableCell>Title</TableCell>
                    <TableCell>Status</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {metrics.recentCases.map(c => (
                    <TableRow key={c.id}>
                      <TableCell sx={{ fontSize: 13 }}>{c.title}</TableCell>
                      <TableCell>
                        <Chip label={c.status.replace('_', ' ')} size="small" color={statusColor[c.status] || 'default'} />
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </Grid>

        {metrics.hotspots.length > 0 && (
          <Grid item xs={12}>
            <Card sx={{ bgcolor: '#FDECEA', border: `1px solid ${BRAND.primary}`, borderRadius: '10px' }}>
              <CardContent>
                <Typography variant="subtitle1" fontWeight={600} mb={1} sx={{ color: BRAND.heading }}>⚠️ Active Hotspots</Typography>
                <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                  {metrics.hotspots.map(h => (
                    <Chip
                      key={h.block}
                      label={`${h.block} — ${h.count} sightings`}
                      variant="outlined"
                      sx={{ borderColor: BRAND.primary, color: BRAND.primary }}
                    />
                  ))}
                </Box>
              </CardContent>
            </Card>
          </Grid>
        )}
      </Grid>
    </Box>
  );
}
